Error at Vercel Deployment
Error: Expected an assignment or function call and instead saw an expression.

Still getting this error.

Some stack overflow boards suggest to refactor from
turnary operater to if/else statement.