Error: At Vercel Deployment
Recieved error at Vercel Deployment:
- Error: Expected an assignment or function call and instead saw an expression.  @typescript-eslint/no-unused-expressions

Reviewing Stackoverflow this may be due to returned
cleanup functions being used in the useEffect hooks.

Have removed them from both ModalToggleButton component
and useLockBodyScroll custom hook.

Tested in local enviroment and SPA modal toggle still functions
as expected.

Pushing to repo now and will attempt another delpoy on Vercel.